### ISSUE TITLE
PA Review: User Auth

### ISSUE THREAD

**Issue by xdeng9** [xdeng9/youcast#2]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components and Containers
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

**Comment by samwalker191** [comment]
- [ ] Navbar/Header has too much space between the top of the window. 
- [ ] Sign in button is a little too big, and corners are a little too round
- [ ] I recommend finding a font to use for your app, Times New Roman isnt the best. 
* https://fonts.google.com/

- [ ] errors on sign up page should be formatted for when there are multiple errors. They are all kinda squished together right now.
- [ ] When clicking on an input in your session form, the border changes to blue, but everything else moves as well. Everything should stay in place when the input is focused. This is usually due to the border increasing in size. You have to compensate for that increase so that it doesn't jiggle everything.

**Comment by xdeng9** [comment]
Issues fixed. I replaced the logout button with a user's logo for now. I will add the drop down to sign out later.
Thanks!

**Comment by samwalker191** [comment]
Looks good! Just needs the drop down menu. I'll consider this MVP done and close the issue.
